# Contents of this file under shared license
defaults: &defaults
  adapter: postgresql
  username: rails5applicationkickoffboost
  password: rails5applicationkickoffboost
  encoding: unicode
  pool: 5
  host: localhost
development:
  <<: *defaults
  database: rails5applicationkickoffboost
test: &test
  <<: *defaults
  database: rails5applicationkickoffboost_test
